name: Start Railway Bot

on:
  schedule:
    - cron: '0 13 * * *'  # 13:00 UTC (6:00 AM PT)
  workflow_dispatch:       # Allow manual trigger

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link Railway Project
        run: railway link --project confident-empathy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Start Railway Service
        run: railway up --service the-real-goosereactor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}


