name: Start Railway Bot

on:
  schedule:
    - cron: '0 13 * * *'  # 6:00 AM PT / 13:00 UTC

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Deploy Service
        run: railway up --service the-real-goosereactor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
