name: Start Railway Bot

on:
  schedule:
    - cron: '0 13 * * *'  # 13:00 UTC (6:00 AM PT)
  workflow_dispatch:       # Manual trigger enabled

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link Railway Project
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway link --project confident-empathy

      - name: Start Railway Service
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway up --service the-real-goosereactor


