name: Start Railway Bot

on:
  schedule:
    - cron: '0 13 * * *'  # 6:00 AM PT / 13:00 UTC

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link to Railway Project
        run: railway link --project 40acd9ea-89d1-4615-913c-48b3bc1262f7
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Debug - List Services
        run: railway status
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Start Railway Service
        run: railway up --service the-real-goosereactor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
