name: Start Railway Bot

on:
  schedule:
    - cron: '0 13 * * *'  # 6:00 AM PT / 13:00 UTC

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Deploy to Railway
        run: npx railway up --service confident-empathy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
