name: Start Railway Bot

on:
  schedule:
    - cron: '0 13 * * *'  # 6 AM PT / 13:00 UTC
  workflow_dispatch:

jobs:
  start:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Start Railway Service
        run: railway up --service the-real-goosereactor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}



