name: Stop Railway Bot

on:
  schedule:
    - cron: '0 5 * * *'  # 10 PM PT / 05:00 UTC
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Stop Railway Service
        run: railway down --service the-real-goosereactor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}




