name: Stop Railway Bot

on:
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link Railway Project
        run: railway link --project confident-empathy
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}

      - name: Stop Railway Service
        run: railway down --service the-real-goosereactor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}



