name: Stop Railway Bot

on:
  schedule:
    - cron: '0 5 * * *'  # 10:00 PM PT / 05:00 UTC

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Stop Railway Service
        run: railway down --project 40acd9ea-89d1-4615-913c-48b3bc1262f7 --service the-real-goosereactor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}
