name: Stop Railway Bot

on:
  schedule:
    - cron: '0 5 * * *'  # 05:00 UTC (10:00 PM PT)
  workflow_dispatch:       # Manual trigger enabled

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Link Railway Project
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway link --project confident-empathy

      - name: Stop Railway Service
        run: |
          export RAILWAY_TOKEN=${{ secrets.RAILWAY_TOKEN }}
          railway down --service the-real-goosereactor




