name: Stop Railway Bot

on:
  schedule:
    - cron: '0 5 * * *'  # Runs daily at 05:00 UTC (10:00 PM PT)
  workflow_dispatch:       # Allows manual trigger

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Stop Railway Service
        run: railway down --service the-real-goosereactor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_TOKEN }}



