name: Stop Railway Bot

on:
  workflow_dispatch:

jobs:
  stop:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Railway CLI
        run: npm install -g @railway/cli

      - name: Set BOT_ACTIVE=false to stop bot
        run: railway variables set BOT_ACTIVE=false --service the-real-goosereactor
        env:
          RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_TOKEN }}




